# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - subtra-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js version
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'

      - name: install, lint, and build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v7
        with:
          name: node-app
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4807D9241BDA4C618C7FF4C5070874D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97CA9FEC106043B3990438F7ABE4B1EA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_171507F1487C428EB5ECD5231698051E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'subtra-web'
          slot-name: 'Production'
          package: .
          